### ISSUE TITLE
Uh... how do I actually use this?

### ISSUE THREAD

**Issue by Skwerps** [Tacogamerman/Cloaked-Gaming-Calculator#3]

**Comment by Skwerps** [comment]
Yeah, but the about:blank cloaking doesn't work, and the algebra unblocker is blocked.

**Comment by Tacogamerman** [comment]
Oh, the about:blank works for me. If the unblocker is blocked for you, I recommend forking and changing the url.

**Comment by cristomald** [comment]
how do i chage the url

**Comment by Tacogamerman** [comment]
You find the link I put in there in the index.html, and change it. I believe it was banana.promathclass.com
